name: Build and Push The Image to Docker Hubi

on:
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps: docker/login-action@v3
    - uses: 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Show current directory
      run: pwd

    - name: List files in current directory
      run: ls -alh
                            
    - name: Build the Docker image
      run: docker build -t sanskrutibagul/wisecow:v1 .
    
        # - name: Docker login
        #run:  docker login -u username -p password 
    - name: push image to docker hub
      run:  docker push sanskrutibagul/wisecow:v1

